// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGRmqLvv3xrPOHhaCsA6VhCU2NLY-Vv28',
    appId: '1:299179969276:web:84b6ba0b8608db6acae579',
    messagingSenderId: '299179969276',
    projectId: 'even-number-2c3c0',
    authDomain: 'even-number-2c3c0.firebaseapp.com',
    storageBucket: 'even-number-2c3c0.firebasestorage.app',
    measurementId: 'G-R51YWS08TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHNJtXlBqSoMUnPH8NFOwgtR7QjkqP_C4',
    appId: '1:299179969276:android:61032feb5e741704cae579',
    messagingSenderId: '299179969276',
    projectId: 'even-number-2c3c0',
    storageBucket: 'even-number-2c3c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVToTI62wQqhYHDvAZwUXgrG9Yh9gqXY',
    appId: '1:299179969276:ios:652bce1f4b2f45bbcae579',
    messagingSenderId: '299179969276',
    projectId: 'even-number-2c3c0',
    storageBucket: 'even-number-2c3c0.firebasestorage.app',
    iosBundleId: 'com.example.evenOdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVToTI62wQqhYHDvAZwUXgrG9Yh9gqXY',
    appId: '1:299179969276:ios:652bce1f4b2f45bbcae579',
    messagingSenderId: '299179969276',
    projectId: 'even-number-2c3c0',
    storageBucket: 'even-number-2c3c0.firebasestorage.app',
    iosBundleId: 'com.example.evenOdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGRmqLvv3xrPOHhaCsA6VhCU2NLY-Vv28',
    appId: '1:299179969276:web:b0f87d2ca68f3c87cae579',
    messagingSenderId: '299179969276',
    projectId: 'even-number-2c3c0',
    authDomain: 'even-number-2c3c0.firebaseapp.com',
    storageBucket: 'even-number-2c3c0.firebasestorage.app',
    measurementId: 'G-KS5604BM46',
  );
}
